### ISSUE TITLE
Issue creating autonumber record

### ISSUE THREAD

**Issue by 23Kev** [BESDev/Celedon-Autonumber-RTM#16]
When creating a new autonumber record to configure autonumbering on any built in entity one of either two errors will occur. 

Environment is D365 v8.2.1.176 on-premises. Autonumber solution version is 1.2.0.0. No other solutions have been installed in this environment. All SDK steps and workflows in autonumber solution are activated/enabled. The error occurs in 2 environments (Prod and UAT) but works fine in 2 others (Dev and SIT).

Config for autonumber
account entity
accountnumber field
Create trigger
2 digits
1 next number

Issue 1 - Account does not exist
![autonumberissue-account does not exist](https://user-images.githubusercontent.com/8153016/33245973-e4d10172-d35a-11e7-9240-ae2318587fe7.png)

Issue 2 - An error has occurred
![autonumberissue-an error has occurred](https://user-images.githubusercontent.com/8153016/33245976-f495a0e0-d35a-11e7-9dae-d2333c6704e7.png)
Error log text.
Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: System.ServiceModel.Security.SecurityNegotiationException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #514974F4Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>1ba109ac-675d-4f8e-8b8b-9a10ba7255b7</ActivityId>
  <ErrorCode>-2147204345</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
    <KeyValuePairOfstringanyType>
      <d2p1:key>CallStack</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">   at Microsoft.Crm.Application.Platform.ServiceCommands.PlatformCommand.XrmExecuteInternal()
   at Microsoft.Crm.Application.Platform.ServiceCommands.CreateCommand.Execute()
   at Microsoft.Crm.Application.Platform.EntityProxy.Create(Boolean performDuplicateCheck, Guid auditingTransactionId)
   at Microsoft.Crm.Application.Platform.EntityProxy.Create(Boolean performDuplicateCheck)
   at Microsoft.Crm.Application.Platform.EntityProxy.CreateAndRetrieve(String[] columnSet, Boolean performDuplicateCheck)
   at Microsoft.Crm.Core.Application.WebServices.InlineEdit.CommandBase.UpdateEntity(Entity entity, Boolean retrieve)
   at Microsoft.Crm.Core.Application.WebServices.InlineEdit.SaveCommand.ExecuteCommand(String commandXml)
   at Microsoft.Crm.Core.Application.WebServices.InlineEdit.CommandBase.Execute(String commandXml, Boolean encodeValues)</d2p1:value>
    </KeyValuePairOfstringanyType>
  </ErrorDetails>
  <Message>System.ServiceModel.Security.SecurityNegotiationException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #514974F4</Message>
  <Timestamp>2017-11-27T00:17:27.8126015Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault i:nil="true" />
  <OriginalException i:nil="true" />
  <TraceText>

[Celedon.AutoNumber: Celedon.CreateAutoNumber]
[d08172ac-6dba-e711-a95e-000d3a301c96: Celedon.CreateAutoNumber: Create of cel_autonumber]
Entered CreateAutoNumber.Execute() : (Correlation Id: 0f55c4ea-5bd2-4783-8e68-9a4123dd3211, Initiating User: f87274a7-c3c9-e711-a2c3-00505698191f)
CreateAutoNumber is firing for Entity: cel_autonumber, Message: Create : (Correlation Id: 0f55c4ea-5bd2-4783-8e68-9a4123dd3211, Initiating User: f87274a7-c3c9-e711-a2c3-00505698191f)
Get Target record : (Correlation Id: 0f55c4ea-5bd2-4783-8e68-9a4123dd3211, Initiating User: f87274a7-c3c9-e711-a2c3-00505698191f)
Check for existing plugin step : (Correlation Id: 0f55c4ea-5bd2-4783-8e68-9a4123dd3211, Initiating User: f87274a7-c3c9-e711-a2c3-00505698191f)
Exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: System.ServiceModel.Security.SecurityNegotiationException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #514974F4 (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault). : (Correlation Id: 0f55c4ea-5bd2-4783-8e68-9a4123dd3211, Initiating User: f87274a7-c3c9-e711-a2c3-00505698191f)
Exiting CreateAutoNumber.Execute() : (Correlation Id: 0f55c4ea-5bd2-4783-8e68-9a4123dd3211, Initiating User: f87274a7-c3c9-e711-a2c3-00505698191f)

</TraceText>
</OrganizationServiceFault>

**Comment by 23Kev** [comment]
Turns out this is an environmental issue. Worth calling out that this is sensitive to authentication configuration. We had a couple of missing SPN's that needed to be reviewed.

**Comment by tsharp** [comment]
Good to know. Do you know what the specifics of the errors were or the exact resolution?
