### ISSUE TITLE
contact Entity does not exist

### ISSUE THREAD

**Issue by jynxeh** [BESDev/Celedon-Autonumber-RTM#21]
Hi,

I have an issue configuring and creating an auto-number in a specific environment and I'm hoping someone can help me track it down. We have auto-numbers configured successfully in DEV but moving to the customer's environment we see different behaviour. Initially, we had an issue with the Sandbox Service which turned out to be a missing port in the backend server firewall (808) but now we have a different error.

The configuration of the environment is version 8.2.2.112 with separate front end and back end servers (1 of each) which is different to dev. When trying to create a new auto-number I get the following business process error:

> Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: contact Entity does not exist.Detail: 
> <OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
>   <ActivityId>d9437b95-2b04-48a6-a8aa-a12da090b276</ActivityId>
>   <ErrorCode>-2147220891</ErrorCode>
>   <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
>     <KeyValuePairOfstringanyType>
>       <d2p1:key>OperationStatus</d2p1:key>
>       <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">0</d2p1:value>
>     </KeyValuePairOfstringanyType>
>     <KeyValuePairOfstringanyType>
>       <d2p1:key>SubErrorCode</d2p1:key>
>       <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">-2146233088</d2p1:value>
>     </KeyValuePairOfstringanyType>
>   </ErrorDetails>
>   <Message>contact Entity does not exist.</Message>
>   <Timestamp>2018-02-01T18:02:03.2921333Z</Timestamp>
>   <ExceptionRetriable>false</ExceptionRetriable>
>   <ExceptionSource i:nil="true" />
>   <InnerFault i:nil="true" />
>   <OriginalException i:nil="true" />
>   <TraceText>
> 
> [Celedon.AutoNumber: Celedon.ValidateAutoNumber]
> [4b9b76ff-6dba-e711-a95e-000d3a301c96: Celedon.ValidateAutoNumber: Create of cel_autonumber]
> 
> Entered ValidateAutoNumber.Execute() : (Correlation Id: 3eabca63-a11e-4cb1-926e-cb679ce71120, Initiating User: 0680d501-d5e3-e711-a2c1-00155d420d3a)
> ValidateAutoNumber is firing for Entity: cel_autonumber, Message: Create : (Correlation Id: 3eabca63-a11e-4cb1-926e-cb679ce71120, Initiating User: 0680d501-d5e3-e711-a2c1-00155d420d3a)
> Getting Target entity : (Correlation Id: 3eabca63-a11e-4cb1-926e-cb679ce71120, Initiating User: 0680d501-d5e3-e711-a2c1-00155d420d3a)
> Validate the Entity name : (Correlation Id: 3eabca63-a11e-4cb1-926e-cb679ce71120, Initiating User: 0680d501-d5e3-e711-a2c1-00155d420d3a)
> Get Attribute List : (Correlation Id: 3eabca63-a11e-4cb1-926e-cb679ce71120, Initiating User: 0680d501-d5e3-e711-a2c1-00155d420d3a)
> Exiting ValidateAutoNumber.Execute() : (Correlation Id: 3eabca63-a11e-4cb1-926e-cb679ce71120, Initiating User: 0680d501-d5e3-e711-a2c1-00155d420d3a)
> 
> </TraceText>
> </OrganizationServiceFault>

I have found a post suggesting this could be related to SPNs but I've checked and believe those are all correct. Any suggestions for either a cause or for an approach to get more logging from Celedon would be greatly appreciated.

Trace on the front end server shows the same error, the backend server has:

> [2018-02-01 18:13:17.980] Process:Microsoft.Crm.Sandbox.WorkerProcess |Organization:00000000-0000-0000-0000-000000000000 |Thread:  269 |Category: Sandbox |User: 00000000-0000-0000-0000-000000000000 |Level: Error |ReqId: 00000000-0000-0000-0000-000000000000 |ActivityId: 61a01e51-2f69-4b7d-822c-7be1f39c9acc | ExceptionConverter.ToSingleFaultOther  ilOffset = 0x30
> >System.ServiceModel.CommunicationObjectFaultedException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #94A16AAB: System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.
> 
> Server stack trace: 
>    at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrImmutable()
>    at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
> 
> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at System.ServiceModel.ICommunicationObject.Open()
>    at Microsoft.Crm.Sandbox.SandboxClientBase`1.Open()
>    at Microsoft.Crm.Sandbox.SandboxClientBase`1.get_Proxy()
>    at Microsoft.Crm.Sandbox.SandboxOrganizationService.Execute(String operation, Byte[] serializedRequest, Object sandboxTraceSettingsObj)

**Comment by umarnazir** [comment]
Hi jynxeh,

I am also using same managed solutions in ms crm 365 v9.  Celedon Auto number solution working fine on DEV but not working on Production servers. I am facing same problem.

**Can you help me how you resolved this issue?**

Below are Servers Info:

**DEV** Infrastructure  
1 Front End Server , DB and Back-end Server Same

Celedon Auto Number Not Working for below 
**Production** Infrastructure  
2 Front End Servers , 2 Back-end Servers, and clustered DB

Thanks

**Comment by jynxeh** [comment]
Hi @umarnazir - to give you hope I did get this sorted, and it was definitely an environmental issue. Unfortunately after trawling my emails I haven't been able to find a convincing solution.

From what I can remember it was down to a blocked port between the front end and back-end servers which is used for fetch XML between the async service and the API. The port is 808 TCP. I'd check this first, if it doesn't sort it let me know and I'll dig deeper.

Good luck!

**Comment by umarnazir** [comment]
Hi, 

Thanks for your your reply. I checked port 808 is opned.

Can you please check your emails and help me to resolve this issue?

Thanks

**Comment by dim895** [comment]
Hello, I do have the same error, did you manage to fix ti?

**Comment by jynxeh** [comment]
So here we are, over two and a half years since my original post and fate decided I should pay for not getting back to you in 2019 @umarnazir. I'm setting up another environment and hit this exact same problem. My Google foo led me back to my own issue (this one) and of course still didn't give me the answer.

After much more pain, hours looking at SPNs, and finally putting WireShark on the server to really dig into what was going on I realised I was right in my April 2019 post, it was port 808, but the trick is it has to be open on BOTH the front end and back end servers. As soon as I opened 808 on the frontend everything started running.

I'm sure this is too late for @umarnazir and @dim895 but hopefully it will help someone else in the future, or maybe me when I forget this next time!
